// Panashe Mushinyi H180534V./Hit400Mobile/src/Chat/cometchat-pro-react-native-ui-kit/src/components/Chats/CometChatConversationListItem/index.js
/* eslint-disable react/no-did-update-set-state */
import React from 'react';
import { CometChat } from '@cometchat-pro/react-native-chat';
import * as enums from '../../../utils/enums';
import {
  CometChatUserPresence,
  CometChatBadgeCount,
  CometChatAvatar,
} from '../../Shared';

import styles from './styles';
import { View, TouchableOpacity, Text } from 'react-native';
import { Platform } from 'react-native';
import { logger } from '../../../utils/common';
import { CometChatContext } from '../../../utils/CometChatContext';

const conversation = 'conversation';
const lastMessage = 'lastMessage';
const deletedAt = 'deletedAt';
const sentAt = 'sentAt';

class CometChatConversationListItem extends React.Component {
  static contextType = CometChatContext;
  constructor(props) {
    super(props);

    this.state = {
      lastMessage: '',
      lastMessageTimestamp: '',
      isThreaded: false,
      restrictions: null,
    };
  }

  componentDidMount() {
    const timestamp = this.getLastMessageTimestamp();

    this.setState({
      lastMessageTimestamp: timestamp,
    });

    this.checkRestrictions();
  }

  checkRestrictions = async () => {
    let isUnreadCountEnabled =
      await this.context.FeatureRestriction.isUnreadCountEnabled();
    let isHideDeletedMessagesEnabled =
      await this.context.FeatureRestriction.isHideDeletedMessagesEnabled();

    this.setState(
      {
        restrictions: { isUnreadCountEnabled, isHideDeletedMessagesEnabled },
      },
      () => {
        const message = this.getLastMessage();
        this.setState({ lastMessage: message || '' });
      },
    );
  };

  componentDidUpdate(prevProps) {
    try {
      const previousItem = JSON.stringify(prevProps.conversation);
      const currentItem = JSON.stringify(this.props.conversation);

      if (previousItem !== currentItem) {
        const message = this.getLastMessage();
        const timestamp = this.getLastMessageTimestamp();

        this.setState({
          lastMessage: message || '',
          lastMessageTimestamp: timestamp,
        });
      }
    } catch (error) {
      logger(error);
    }
  }

  /**
   * Retrieve last message from conversation object
   * @param
   */
  getLastMessage = () => {
    try {
      if (
        Object.prototype.hasOwnProperty.call(this.props, conversation) === false
      ) {
        return false;
      }

      if (
        Object.prototype.hasOwnProperty.call(
          this.props.conversation,
          lastMessage,
        ) === false
      ) {
        return false;
      }

      let message = null;
      const { lastMessage: lastMessageObject } = this.props.conversation;

      if (Object.prototype.hasOwnProperty.call(lastMessageObject, deletedAt)) {
        if (this.state?.restrictions?.isHideDeletedMessagesEnabled) {
          message = '';
        } else {
          message =
            this.props.loggedInUser.uid === lastMessageObject.sender.uid
              ? '⚠ You deleted this message.'
              : '⚠ This message was deleted.';
        }
      } else {
        switch (lastMessageObject.category) {
          case 'message':
            message = this.getMessage(lastMessageObject);
            break;
          case 'call':
            message = this.getCallMessage(lastMessageObject);
            break;
          case 'action':
            message = lastMessageObject.message;
            break;
          case 'custom':
            message = this.getCustomMessage(lastMessageObject);
            break;
          default:
            break;
        }
      }

      return message;
    } catch (error) {
      logger(error);
    }
  };

  /**
   * Retrieve last message timestamp from conversation object
   * @param
   */
  getLastMessageTimestamp = () => {
    try {
      if (
        Object.prototype.hasOwnProperty.call(this.props, conversation) === false
      ) {
        return false;
      }

      if (
        Object.prototype.hasOwnProperty.call(
          this.props.conversation,
          lastMessage,
        ) === false
      ) {
        return false;
      }

      if (
        Object.prototype.hasOwnProperty.call(
          this.props.conversation.lastMessage,
          sentAt,
        ) === false
      ) {
        return false;
      }

      let timestamp = null;

      const messageTimestamp = new Date(
        this.props.conversation.lastMessage.sentAt * 1000,
      );
      const currentTimestamp = Date.now();

      const diffTimestamp = currentTimestamp - messageTimestamp;

      if (diffTimestamp < 24 * 60 * 60 * 1000) {
        timestamp = messageTimestamp.toLocaleTimeString('en-US', {
          hour: 'numeric',
          minute: 'numeric',
          hour12: true,
        });
        if (Platform.OS === 'android' && timestamp !== 'Yesterday') {
          let time = timestamp.split(':'); // convert to array

          var hours = Number(time[0]);
          var minutes = Number(time[1]?.split(' ')[0]);
          var timeValue;

          if (hours > 0 && hours <= 12) {
            timeValue = '' + hours;
          } else if (hours > 12) {
            timeValue = '' + (hours - 12);
          } else if (hours == 0) {
            timeValue = '12';
          }

          timeValue += minutes < 10 ? ':0' + minutes : ':' + minutes; // get minutes
          timeValue += hours >= 12 ? ' PM' : ' AM'; // get AM/PM
          timestamp = timeValue;
        }
      } else if (diffTimestamp < 48 * 60 * 60 * 1000) {
        timestamp = 'Yesterday';
      } else if (diffTimestamp < 7 * 24 * 60 * 60 * 1000) {
        timestamp = messageTimestamp.toLocaleDateString('en-US', {
          year: '2-digit',
          month: '2-digit',
          day: '2-digit',
        });
      } else {
        timestamp = messageTimestamp.toLocaleDateString('en-US', {
          year: '2-digit',
          month: '2-digit',
          day: '2-digit',
        });
      }

      return timestamp;
    } catch (error) {
      logger(error);
    }
  };

  /**
   * Retrieve last message for messageType - custom
   * @param lastMessage - message object
   */
  getCustomMessage = (lastMessage) => {
    try {
      let message = null;
      switch (lastMessage.type) {
        case enums.CUSTOM_TYPE_POLL:
          message = 'Poll';
          break;
        case enums.CUSTOM_TYPE_STICKER:
          message = 'Sticker';
          break;
        case 'meeting':
          message = 'Video Call';
          break;
        default:
          break;
      }

      return message;
    } catch (error) {
      logger(error);
    }
  };

  /**
   * Retrieve last message for messageType - message
   * @param lastMessage - message object
   */
  getMessage = (lastMessage) => {
    try {
      let message = null;
      this.setState({ isThreaded: lastMessage.parentMessageId });
      switch (lastMessage.type) {
        case CometChat.MESSAGE_TYPE.TEXT:
          message = lastMessage.text;
          break;
        case CometChat.MESSAGE_TYPE.MEDIA:
          message = 'Media message';
          break;
        case CometChat.MESSAGE_TYPE.IMAGE:
          message = '📷 Image ';
          break;
        case CometChat.MESSAGE_TYPE.FILE:
          message = '📁 File';
          break;
        case CometChat.MESSAGE_TYPE.VIDEO:
          message = '🎥 Video';
          break;
        case CometChat.MESSAGE_TYPE.AUDIO:
          message = '🎵 Audio';
          break;
        case CometChat.MESSAGE_TYPE.CUSTOM:
          message = 'Custom message';
          break;
        default:
          break;
      }

      return message;
    } catch (error) {
      logger(error);
    }
  };

  /**
   * Retrieve last message for messageType - call
   * @param lastMessage - message object
   */
  getCallMessage = (lastMessage) => {
    try {
      let message = null;
      switch (lastMessage.type) {
        case CometChat.MESSAGE_TYPE.VIDEO:
          message = 'Video call';
          break;
        case CometChat.MESSAGE_TYPE.AUDIO:
          message = 'Audio call';
          break;
        default:
          break;
      }

      return message;
    } catch (error) {
      logger(error);
    }
  };

  /**
   * Retrieve avatar from conversation object
   * @param
   */
  getAvatar = () => {
    try {
      let avatar;
      if (this.props.conversation.conversationType === 'user') {
        avatar = { uri: this.props.conversation.conversationWith.avatar };
      } else if (this.props.conversation.conversationType === 'group') {
        avatar = { uri: this.props.conversation.conversationWith.icon };
      }
      return avatar;
    } catch (error) {
      logger(error);
    }
  };

  render() {
    let lastMessageTimeStamp = null;
    if (this.state.lastMessage) {
      lastMessageTimeStamp = (
        <Text style={styles.itemLastMsgTimeStyle} numberOfLines={1}>
          {this.state.lastMessageTimestamp}
        </Text>
      );
    }

    let presence;

    if (this.props.conversation.conversationType === 'user') {
      const { status } = this.props.conversation.conversationWith;
      presence = (
        <CometChatUserPresence
          status={status}
          style={{ top: 30 }}
          cornerRadius={18}
          borderColor={this.props.theme.color.white}
          borderWidth={2}
        />
      );
    }
    return (
      <View key={this.props?.conversation?.conversationId}>
        <TouchableOpacity
          activeOpacity={1}
          underlayColor={this.props.theme.backgroundColor.listUnderlayColor}
          style={styles.listItem}
          onPress={() => {
            /* console.log(this.props.handleClick); */
            this.props.handleClick(
              this.props.conversation,
              this.props.conversationKey,
            );
          }}>
          <View style={styles.itemThumbnailStyle}>
            <CometChatAvatar
              image={this.getAvatar()}
              cornerRadius={25}
              borderColor={this.props.theme.color.secondary}
              borderWidth={0}
              name={this.props.conversation.conversationWith.name}
            />
            {presence}
          </View>
          <View
            style={[
              styles.itemDetailsContainer,
              { borderBottomColor: this.props.theme.borderColor.primary },
            ]}>
            <View
              style={{
                flexDirection: 'row',
                justifyContent: 'space-between',
                width: '100%',
                alignItems: 'center',
              }}>
              <Text numberOfLines={1} style={styles.itemNameStyle}>
                {this.props.conversation.conversationWith.name}
              </Text>
              <View style={styles.itemLastMsgStyle}>
                {lastMessageTimeStamp}
              </View>
            </View>
            <View
              style={{
                flexDirection: 'row',
                justifyContent: 'space-between',
                width: '100%',
                alignItems: 'center',
              }}>
              <Text numberOfLines={1} style={styles.itemLastMsgTimeStyle}>
                {`${this.state.isThreaded ? 'In a thread : ' : ''}` +
                  this.state.lastMessage}
              </Text>

              {this.state.restrictions?.isUnreadCountEnabled ? (
                <CometChatBadgeCount
                  theme={this.props.theme}
                  count={this.props.conversation.unreadMessageCount}
                />
              ) : null}
            </View>
          </View>
        </TouchableOpacity>
      </View>
    );
  }
}
export default CometChatConversationListItem;

// Panashe Mushinyi H180534V./Hit400Dashboard/src/components/InboxChat/src/components/Chats/CometChatConversationListItem/CometChatConversationListItem.vue
<template>
    <div
        class="chat__item--hover"
        :style="styles.list"
        @click="itemClickHandler"
        @mouseenter="handleMouseHover(true)"
        @mouseleave="handleMouseHover(false)"
    >
        <div :style="styles.thumbnail">
            <comet-chat-avatar
                border-width="1px"
                corner-radius="18px"
                :image="getAvatar()"
                :border-color="theme.borderColor.primary"
            />
            <comet-chat-user-presence
                border-width="1px"
                corner-radius="50%"
                :border-color="theme.borderColor.primary"
                :status="conversation.conversationWith.status"
                v-if="conversation.conversationType === 'user'"
            />
        </div>
        <div :style="styles.detail">
            <div :style="styles.row">
                <div
                    class="name"
                    :style="styles.name"
                    @mouseenter="toggleTooltip($event, true)"
                    @mouseleave="toggleTooltip($event, false)"
                >
                    {{ conversation.conversationWith.name }}
                </div>
                <span
                    :style="styles.lastMsgTime"
                    class="item__details__timestamp"
                    v-if="conversation.lastMessage"
                    >{{ getLastMessageTime() }}</span
                >
            </div>
            <div :style="styles.row">
                <div
                    :style="styles.lastMsg"
                    @mouseenter="toggleTooltip($event, true)"
                    @mouseleave="toggleTooltip($event, false)"
                >
                    {{ getLastMessage() }}
                </div>
                <comet-chat-badge-count
                    :theme="theme"
                    :count="conversation.unreadMessageCount"
                />
            </div>
            <div v-if="isHovering">
                <cometchat-conversation-list-actions
                    :theme="theme"
                    :conversation="conversation"
                />
            </div>
        </div>
    </div>
</template>
<script>
/*eslint-disable*/

import dateFormat from 'dateformat'
import { CometChat } from '@cometchat-pro/chat'
import {
    COMETCHAT_CONSTANTS,
    DEFAULT_OBJECT_PROP,
} from '../../../resources/constants'

import { cometChatCommon, propertyCheck, tooltip } from '../../../mixins/'
import * as enums from '../../../util/enums.js'

import {
    CometChatAvatar,
    CometChatBadgeCount,
    CometChatUserPresence,
} from '../../Shared/'
import cometchatConversationListActions from '../CometChatConversationListActions/index.vue'

import * as style from './style'

/**
 * The conversation item for conversation list.
 *
 * @displayName CometChatConversationListItem
 */
export default {
    name: 'CometChatConversationListItem',
    mixins: [tooltip, propertyCheck, cometChatCommon],
    components: {
        CometChatAvatar,
        CometChatBadgeCount,
        CometChatUserPresence,
        cometchatConversationListActions,
    },
    props: {
        /**
         * Theme of the UI.
         */
        theme: { ...DEFAULT_OBJECT_PROP },
        /**
         * @ignore
         */
        config: { ...DEFAULT_OBJECT_PROP },
        /**
         * Current logged in user.
         */
        loggedInUser: { ...DEFAULT_OBJECT_PROP },
        /**
         * Current conversation object.
         */
        conversation: { ...DEFAULT_OBJECT_PROP },
        /**
         * Selected conversation object.
         */
        selectedConversation: { ...DEFAULT_OBJECT_PROP },
    },
    data() {
        return {
            isHovering: false,
        }
    },
    computed: {
        /**
         * Computed styles for the component.
         */
        styles() {
            return {
                list: style.listItem(
                    this.theme,
                    this.conversation,
                    this.selectedConversation
                ),
                row: style.itemRowStyle(),
                name: style.itemNameStyle(),
                detail: style.itemDetailStyle(),
                thumbnail: style.itemThumbnailStyle(),
                lastMsg: style.itemLastMsgStyle(this.theme),
                lastMsgTime: style.itemLastMsgTimeStyle(this.theme),
            }
        },
    },
    methods: {
        /**
         * Handles item click
         */
        itemClickHandler() {
            this.emitEvent('click', {
                item: this.conversation.conversationWith,
                type: this.conversation.conversationType,
            })
        },
        handleMouseHover(toggleFlag) {
            if (toggleFlag && !this.isHovering) {
                this.isHovering = true
            } else if (!toggleFlag && this.isHovering) {
                this.isHovering = false
            }
        },
        /**
         * Gets SVG avatar
         */
        getAvatar() {
            let avatar
            if (this.conversation.conversationType === 'user') {
                avatar = this.conversation.conversationWith.avatar
            } else if (this.conversation.conversationType === 'group') {
                avatar = this.conversation.conversationWith.icon
            }
            return avatar
        },
        /**
         * Gets last message time
         */
        getLastMessageTime() {
            if (!this.conversation) {
                return false
            }

            if (this.hasProperty(this.conversation, 'lastMessage') === false) {
                return false
            }

            if (
                this.hasProperty(this.conversation.lastMessage, 'sentAt') ===
                false
            ) {
                return false
            }

            let timestamp = null

            const messageTimestamp = new Date(
                this.conversation.lastMessage.sentAt * 1000
            )
            const currentTimestamp = Date.now()

            const diffTimestamp = currentTimestamp - messageTimestamp

            if (diffTimestamp < 24 * 60 * 60 * 1000) {
                timestamp = dateFormat(messageTimestamp, 'shortTime')
            } else if (diffTimestamp < 48 * 60 * 60 * 1000) {
                timestamp = COMETCHAT_CONSTANTS.YESTERDAY
            } else if (diffTimestamp < 7 * 24 * 60 * 60 * 1000) {
                timestamp = dateFormat(messageTimestamp, 'dddd')
            } else {
                timestamp = dateFormat(messageTimestamp, 'dd/mm/yyyy')
            }

            return timestamp
        },
        getLastMessage() {
            if (!this.conversation.lastMessage) return ''

            const lastMessage = this.conversation.lastMessage

            let message = null
            if (this.hasProperty(lastMessage, 'deletedAt')) {
                message =
                    this.loggedInUser.uid === lastMessage.sender.uid
                        ? COMETCHAT_CONSTANTS.YOU_DELETED_THIS_MESSAGE
                        : COMETCHAT_CONSTANTS.THIS_MESSAGE_DELETED
            } else {
                switch (lastMessage.category) {
                    case 'message':
                        message = this.getMessage(lastMessage)
                        break
                    case 'call':
                        message = this.getCallMessage(lastMessage)
                        break
                    case 'action':
                        message = lastMessage.message
                        break
                    case 'custom':
                        message = this.getCustomMessage(lastMessage)
                        break
                    default:
                        break
                }
            }
            return message
        },
        getMessage(lastMessage) {
            let message = ''
            switch (lastMessage.type) {
                case CometChat.MESSAGE_TYPE.TEXT:
                    message = lastMessage.text
                    break
                case CometChat.MESSAGE_TYPE.MEDIA:
                    message = COMETCHAT_CONSTANTS.MEDIA_MESSAGE
                    break
                case CometChat.MESSAGE_TYPE.IMAGE:
                    message = COMETCHAT_CONSTANTS.MESSAGE_IMAGE
                    break
                case CometChat.MESSAGE_TYPE.FILE:
                    message = COMETCHAT_CONSTANTS.MESSAGE_FILE
                    break
                case CometChat.MESSAGE_TYPE.VIDEO:
                    message = COMETCHAT_CONSTANTS.MESSAGE_VIDEO
                    break
                case CometChat.MESSAGE_TYPE.AUDIO:
                    message = COMETCHAT_CONSTANTS.MESSAGE_AUDIO
                    break
                case CometChat.MESSAGE_TYPE.CUSTOM:
                    message = COMETCHAT_CONSTANTS.CUSTOM_MESSAGE
                    break
                default:
                    break
            }

            return message
        },
        getCallMessage(lastMessage) {
            let message = ''
            const type = lastMessage.type

            switch (type) {
                case CometChat.MESSAGE_TYPE.VIDEO:
                    message = COMETCHAT_CONSTANTS.VIDEO_CALL
                    break
                case CometChat.MESSAGE_TYPE.AUDIO:
                    message = COMETCHAT_CONSTANTS.AUDIO_CALL
                    break
                default:
                    break
            }

            return message
        },
        getCustomMessage(lastMessage) {
            let message = ''
            switch (lastMessage.type) {
                case enums.CUSTOM_TYPE_POLL:
                    message = COMETCHAT_CONSTANTS.CUSTOM_MESSAGE_POLL
                    break
                case enums.CUSTOM_TYPE_STICKER:
                    message = COMETCHAT_CONSTANTS.CUSTOM_MESSAGE_STICKER
                    break
                case enums.CUSTOM_TYPE_DOCUMENT:
                    message = COMETCHAT_CONSTANTS.CUSTOM_MESSAGE_DOCUMENT
                    break
                default:
                    break
            }

            return message
        },
    },
}
</script>
<style scoped>
.chat__item--hover:hover {
    background-color: var(--chat-item-bg-color-hover);
}
.light {
}

.name {
    color: #333333;
}
</style>
